apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config 
  namespace: default 
  labels:
    app: nginx 

data:
  nginx.conf: |
    server {
        listen {{ .Values.nginx.inner_port }} default_server;
        server_name _;  
        root /usr/share/nginx/html;
        index index.html, index.php;
        location ~ \.php$ {
            fastcgi_pass {{ .Values.phpfpm.host }}:{{ .Values.phpfpm.inner_port }}; 
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
        location / {
            try_files $uri $uri/ =404;
        }
    }


