apiVersion: v1
kind: ConfigMap
metadata:
  name: phpmyadmin-config 
  namespace: default 
  labels:
    app: phpmyadmin 

data:
  PMA_HOST: {{ .Values.mysql.host }}
  PMA_PORT: {{ .Values.mysql.inner_port | quote }}
  PMA_USER: {{ .Values.mysql.user }}
  PMA_PASS: {{ .Values.mysql.root_password }}
  APACHE_SERVER_NAME: {{ .Values.phpmyadmin.apache_server_name }}
  PMA_ARBITRARY: "1" 
  config.inc.php: |
    <?php
    $cfg['Servers'][1]['auth_type'] = 'config';
    $cfg['Servers'][1]['host'] = getenv('PMA_HOST') ?: 'mysql';
    $cfg['Servers'][1]['port'] = getenv('PMA_PORT') ?: '3306';
    $cfg['Servers'][1]['user'] = getenv('PMA_USER'); 
    $cfg['Servers'][1]['password'] = getenv('PMA_PASS'); 


